language: java
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e19597da4fac_key -iv $encrypted_e19597da4fac_iv
  -in pgp.asc.enc -out pgp.asc -d
- gpg --fast-import pgp.asc
before_script: mvn javadoc:javadoc -DskipTests=true -B -V
script: mvn clean install
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  #GPG_PASSPHRASE
  - secure: YqXA0mY5JW3EwtKQjWLMD7Q4dpHVoIpfgYjG2D1D2X67KfekN6h5NaQWCQsPV0AJvznbF/bWoNjUGscncukA2MW/Fz1kXmnnuFmsFQNQAYBCilO5L8/MPWd0UFmHNJQYq5NGw9ajduB46E8K3URMPzseZsZo6IPalJ9i1VKF/Cg=
deploy:
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: Ca89OLPkZ/qQ4/Ky2FBy7V0gFlhD8MGPWKLFI0FX/yCJn5I3ZmzSEIFBozym1HmG23zdofB2RfVn11c4EF1hjh2r3XUjucBV5L8xN0BLtA8s82OALBilfD+tmvUzhWUP7sG2enyeoAYFF+mNxkRFz4rx3Wn/tP1qeHDD54UNyUo=
  on:
    tags: true
  file:
  - sejda-distribution/target/*.zip
- provider: script
  script: mvn deploy --settings .travis.settings.xml
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
  - info@sejda.org
